// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejtjavrvpzoahaelevn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lanRqYXZydnB6b2FoYWVsZXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTA1NDUsImV4cCI6MjA2OTE4NjU0NX0.uiB79kcIHq6cn79Ctmcz4-OnhD8qfv6ISml6O0FZLSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});